services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5005:5005"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"